Repository agroal/pgagroal, pull requests merged in 2024-03, with the labels that each got.

#411 [#403][#410] Improve error messages for pgagroal-cli
  src/admin.c
  src/cli.c
  src/include/utils.h
  src/libpgagroal/utils.c
Labels: enhancement

#414 Fix connection errors
  src/libpgagroal/management.c
Labels: bug

#427 Enable PostgreSQL and run pgagroal-cli status in CI
  .github/workflows/ci.yml
Labels: feature

#407 WIP: pgagroal-vault
  AUTHORS
  doc/CONFIGURATION.md
  doc/VAULT.md
  doc/etc/pgagroal_vault.conf
  doc/man/pgagroal-admin.1.rst
  doc/man/pgagroal-cli.1.rst
  doc/man/pgagroal-vault.1.rst
  doc/man/pgagroal.1.rst
  doc/man/pgagroal.conf.5.rst
  doc/man/pgagroal_databases.conf.5.rst
  doc/man/pgagroal_hba.conf.5.rst
  doc/man/pgagroal_vault.conf.5.rst
  doc/tutorial/06_vault.md
  pgagroal.spec
  src/CMakeLists.txt
  src/admin.c
  src/cli.c
  src/include/configuration.h
  src/include/management.h
  src/include/network.h
  src/include/pgagroal.h
  src/include/security.h
  src/include/utils.h
  src/libpgagroal/configuration.c
  src/libpgagroal/logging.c
  src/libpgagroal/management.c
  src/libpgagroal/memory.c
  src/libpgagroal/network.c
  src/libpgagroal/pipeline_perf.c
  src/libpgagroal/pipeline_session.c
  src/libpgagroal/pipeline_transaction.c
  src/libpgagroal/pool.c
  src/libpgagroal/prometheus.c
  src/libpgagroal/remote.c
  src/libpgagroal/security.c
  src/libpgagroal/server.c
  src/libpgagroal/shmem.c
  src/libpgagroal/tracker.c
  src/libpgagroal/utils.c
  src/libpgagroal/worker.c
  src/main.c
  src/vault.c
Labels: feature
