Repository agroal/pgagroal, pull requests merged in 2025-07, with the labels that each got.

#584 [#583] Add manual for core APIs
  doc/DEVELOPERS.md
  doc/manual/advanced/99-references.md
  doc/manual/advanced/dev-07-core_api.md
Labels: documentation

#593 [#592] Introduce ValueNone and get_typed functions
  doc/manual/dev-07-core_api.md
  src/include/art.h
  src/include/json.h
  src/include/value.h
  src/libpgagroal/art.c
  src/libpgagroal/json.c
  src/libpgagroal/value.c
Labels: enhancement

#594 [#521] Add directory configuration option
  doc/CONFIGURATION.md
  doc/GETTING_STARTED.md
  doc/man/pgagroal.1.rst
  doc/manual/advanced/04-configuration.md
  doc/manual/user-01-quickstart.md
  doc/manual/user-02-configuration.md
  src/include/utils.h
  src/libpgagroal/utils.c
  src/main.c
Labels: feature
